// Package project handles reading and writing the .lambit.toml project file,
// which describes the lambda functions, test cases, and data models for a
// project that lambit is invoked in.
package project

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/BurntSushi/toml"
)

const ProjectFile = ".lambit.toml"

// TestCase is a named payload that can be passed to a function.
type TestCase struct {
	Name    string `toml:"name"`
	Payload string `toml:"payload"`
}

// Function describes a discoverable lambda handler entry point.
type Function struct {
	Name        string     `toml:"name"`
	Handler     string     `toml:"handler"`     // e.g. "MyFn::MyFn.Function::FunctionHandler"
	Description string     `toml:"description"` // optional
	Tests       []TestCase `toml:"tests"`
}

// Model is a named JSON blob that can be used as a payload template.
type Model struct {
	Name string `toml:"name"`
	JSON string `toml:"json"`
}

// Project is the root struct for .lambit.toml.
type Project struct {
	// Path is the directory where .lambit.toml lives (not persisted).
	Path string `toml:"-"`

	Name      string     `toml:"name"`
	Runtime   string     `toml:"runtime"` // override auto-detect, e.g. "dotnet", "nodejs"
	APIPort   int        `toml:"api_port"`
	Functions []Function `toml:"functions"`
	Models    []Model    `toml:"models"`
}

// DefaultAPIPort is used when the project file omits api_port.
const DefaultAPIPort = 8080

// Load reads .lambit.toml from dir (or any ancestor directory).
// Returns ErrNotFound if no project file exists anywhere in the tree.
func Load(dir string) (*Project, error) {
	path, err := findProjectFile(dir)
	if err != nil {
		return nil, err
	}

	p := &Project{}
	if _, err := toml.DecodeFile(path, p); err != nil {
		return nil, fmt.Errorf("parsing %s: %w", path, err)
	}
	p.Path = filepath.Dir(path)
	if p.APIPort == 0 {
		p.APIPort = DefaultAPIPort
	}
	return p, nil
}

// Save writes the project back to its .lambit.toml file.
func Save(p *Project) error {
	path := filepath.Join(p.Path, ProjectFile)
	return os.WriteFile(path, []byte(buildProjectTOML(p)), 0644)
}

// Scaffold writes a .lambit.toml to dir (does not overwrite an existing one).
//
// If detected is non-empty the discovered functions are used as the initial
// function list, giving the user a head-start over the generic placeholder.
// Each function that has no test cases gets a default "Hello world" test added
// so there is always something to invoke immediately.
//
// If detected is empty the classic hardcoded placeholder is used instead.
func Scaffold(dir string, detected []Function) error {
	path := filepath.Join(dir, ProjectFile)
	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("%s already exists", path)
	}

	var functions []Function
	if len(detected) > 0 {
		for _, fn := range detected {
			if len(fn.Tests) == 0 {
				fn.Tests = []TestCase{
					{Name: "Hello world", Payload: `{"input": "hello world"}`},
				}
			}
			functions = append(functions, fn)
		}
	} else {
		functions = []Function{
			{
				Name:        "FunctionHandler",
				Handler:     "MyFunction::MyFunction.Function::FunctionHandler",
				Description: "Main lambda entry point — update the handler string above",
				Tests: []TestCase{
					{Name: "Hello world", Payload: `{"input": "hello world"}`},
				},
			},
		}
	}

	p := &Project{
		Path:      dir,
		Name:      filepath.Base(dir),
		Runtime:   "",
		APIPort:   DefaultAPIPort,
		Functions: functions,
		Models: []Model{
			{Name: "SamplePayload", JSON: `{"key": "value", "count": 1}`},
		},
	}
	return os.WriteFile(path, []byte(buildProjectTOML(p)), 0644)
}

// ErrNotFound is returned when no project file is found.
var ErrNotFound = fmt.Errorf("no %s found in this directory or any parent", ProjectFile)

// findProjectFile walks up from dir looking for a .lambit.toml file.
func findProjectFile(dir string) (string, error) {
	cur := dir
	for {
		candidate := filepath.Join(cur, ProjectFile)
		if _, err := os.Stat(candidate); err == nil {
			return candidate, nil
		}
		parent := filepath.Dir(cur)
		if parent == cur {
			break
		}
		cur = parent
	}
	return "", ErrNotFound
}

// buildProjectTOML serialises a Project to TOML text.
func buildProjectTOML(p *Project) string {
	out := "# lambit project file\n" +
		"# Generated by lambit — edit freely.\n\n" +
		"[project]\n" +
		"name     = " + quote(p.Name) + "\n" +
		"runtime  = " + quote(p.Runtime) + "  # leave empty for auto-detect\n" +
		"api_port = " + itoa(p.APIPort) + "\n"

	for _, fn := range p.Functions {
		out += "\n[[functions]]\n"
		out += "name        = " + quote(fn.Name) + "\n"
		out += "handler     = " + quote(fn.Handler) + "\n"
		out += "description = " + quote(fn.Description) + "\n"
		for _, t := range fn.Tests {
			out += "\n[[functions.tests]]\n"
			out += "name    = " + quote(t.Name) + "\n"
			out += "payload = " + singleQuote(t.Payload) + "\n"
		}
	}

	for _, m := range p.Models {
		out += "\n[[models]]\n"
		out += "name = " + quote(m.Name) + "\n"
		out += "json = " + singleQuote(m.JSON) + "\n"
	}

	return out
}

func quote(s string) string       { return `"` + s + `"` }
func singleQuote(s string) string { return "'" + s + "'" }
func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	buf := [20]byte{}
	pos := len(buf)
	for n > 0 {
		pos--
		buf[pos] = byte('0' + n%10)
		n /= 10
	}
	return string(buf[pos:])
}
